-- creamos la base de datos del hotel.
CREATE DATABASE Hotel;
USE Hotel;

CREATE SCHEMA USUARIOS;
CREATE SCHEMA RESERVA;
CREATE SCHEMA FACTURACION;
CREATE SCHEMA HABITACION;

CREATE TABLE USUARIOS.Usuarios(
	idUsuario INT IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(20),
	apellidos VARCHAR(20),
	dui VARCHAR(10),
	correo VARCHAR(25),
	edad INT,
	numeroTelefonico VARCHAR(8),
	numPersonas INT,
	Presupuesto FLOAT(5)
);

--crear logins
CREATE LOGIN ReneFuentes WITH PASSWORD = 'FazbearJones';
CREATE LOGIN HectorFranco WITH PASSWORD = 'HitTheFan';
CREATE LOGIN ArnoldoHernandez WITH PASSWORD = 'pipipi';
CREATE LOGIN GeovannyAlvarez WITH PASSWORD = 'FCB';

CREATE USER ReneFuetes FOR LOGIN ReneFuentes WITH DEFAULT_SCHEMA = RESERVA;
CREATE USER Franco FOR LOGIN HectorFranco WITH DEFAULT_SCHEMA = USUARIOS;
CREATE USER Arnoldo FOR LOGIN ArnoldoHernandez WITH DEFAULT_SCHEMA = FACTURACION;
CREATE USER Mauro FOR LOGIN GeovannyAlvarez WITH DEFAULT_SCHEMA = HABITACION;

--dar permisos
--Rene
GRANT ALTER ON SCHEMA::RESERVA TO ReneFuetes;
GRANT CREATE TABLE TO ReneFuetes;
GRANT REFERENCES ON SCHEMA::RESERVA TO ReneFuetes;

--Arnoldo
GRANT ALTER ON SCHEMA::FACTURACION TO Arnoldo;
GRANT CREATE TABLE TO Arnoldo;
GRANT REFERENCES ON SCHEMA::FACTURACION TO Arnoldo;
GRANT INSERT ON FACTURACION.facturacion TO Arnoldo;
GRANT SELECT ON FACTURACION.facturacion TO Arnoldo;

CREATE TABLE FACTURACION.facturacion(
	idFacturacion INT IDENTITY(1,1) PRIMARY KEY,
	total INT,
	detalles VARCHAR(40),
	comentarios VARCHAR(40));
